### ISSUE TITLE
Light client support

### ISSUE THREAD

**Issue by ltfschoen** [hicommonwealth/edgeware-lockdrop#16]
Suggestion to use Parity Light.js instead of Web3.js so users can connect to a Parity "Light Client" Node instead of having to use a "Full Node" that we trust, or having to fallback to Infura. 

See https://matrix.to/#/!AtgPynFxLJGFYkAZEl:matrix.parity.io/$1559688870138068XFOqe:matrix.org?via=matrix.parity.io&via=matrix.org

For example, if I run a Parity Ethereum "Light Client" Node that's fully synchronised with `./target/release/parity --light --chain ropsten` and then query balances with Edgeware CLI with `node scripts/lockdrop.js --balance` it returns:
```
Fetching Lockdrop balance from lockdrop contract 0x111ee804560787E0bFC1898ed79DAe24F2457a04

Error: Unknown block number
    at /home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:15:625714
    at e.i.onreadystatechange (/home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:15:780374)
    at e.t.dispatchEvent (/home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:1:156918)
    at e._setReadyState (/home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:15:785136)
    at e._onHttpResponseEnd (/home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:15:788221)
    at IncomingMessage.<anonymous> (/home/me/code/github/me/edgeware-lockdrop/node_modules/truffle-hdwallet-provider/dist/index.js:15:787479)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:9739) UnhandledPromiseRejectionWarning: Error: Requested data size exceeds limit of 1000 blocks.
...
```

But if I run a Parity Ethereum "Full Node" with ``./target/release/parity --chain ropsten` and then query balances with Edgeware CLI with `node scripts/lockdrop.js --balance` it correctly returns the balances:
```
Total ETH locked: 7.601
Total ETH signaled: 0.69685286
```

**Comment by drewstone** [comment]
Ok I will look into this. Does using the Parity Light.js library make us lose anything in this case? Can you still connect to full nodes? @ltfschoen

**Comment by drewstone** [comment]
Hi @ltfschoen after looking at this, it seems with learning the new light.js API and swapping out all the logic (including contract data marshalling) that I am not going to be prioritising this. We however welcome commits and I will review work when/if it is ready.

**Comment by ltfschoen** [comment]
@drewstone, Light.js should work with both full nodes and light nodes. I'd have to actually implement it on the Edgewa.re repo to know for sure that there are no issues. Unfortunately I'm focusing on Rust for the next couple of months but will look into it after that if there's still a need.
