### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Requested data size exceeds limit of 1000 blocks.

### ISSUE THREAD

**Issue by soc1c** [hicommonwealth/edgeware-lockdrop#6]
Hi, trying to query my balance:

```
~/.opt/edge-lockdrop master
❯ node ./scripts/lockdrop.js --balance
Fetching Lockdrop balance...

(node:29824) UnhandledPromiseRejectionWarning: Error: Returned error: Requested data size exceeds limit of 1000 blocks.
    at Object.ErrorResponse (/home/user/.opt/edge-lockdrop/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/user/.opt/edge-lockdrop/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/home/user/.opt/edge-lockdrop/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/user/.opt/edge-lockdrop/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/user/.opt/edge-lockdrop/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/user/.opt/edge-lockdrop/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/user/.opt/edge-lockdrop/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:29824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Truffle 5, Node 10, Arch Linux:

```
~/.opt/edge-lockdrop 15s
❯ uname -a
Linux ceres 4.20.13-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 27 19:10:28 UTC 2019 x86_64 GNU/Linux

~/.opt/edge-lockdrop
❯ yarn --version
1.15.2

~/.opt/edge-lockdrop
❯ node --version
v10.15.3

~/.opt/edge-lockdrop
❯ truffle version  
Truffle v5.0.8 (core: 5.0.8)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
```

Connected to a Parity default-config light node on mainnet:

```
❯ parity --light
2019-03-18 10:01:43  Starting Parity-Ethereum/v2.3.5-stable-ebd0fd0117-20190227/x86_64-linux-gnu/rustc1.32.0
2019-03-18 10:01:43  Keys path /home/user/.local/share/io.parity.ethereum/keys/ethereum
2019-03-18 10:01:43  DB path /home/user/.local/share/io.parity.ethereum/chains_light/ethereum/db/906a34e69aec8c0d
2019-03-18 10:01:43  Running in experimental Light Client mode.
2019-03-18 10:01:43  Debug API is not available in light client mode.
2019-03-18 10:01:43  Debug API is not available in light client mode.
2019-03-18 10:01:43  Public node URL: enode://e2ea472bcbf28c3a5784e34f6ca05cca9c87779885af013eaf3ecc4d0f213e19a20f4170b83945631507b84187368df51dcb15011da4f2c125e9a1e58f258934@192.168.0.196:30303
2019-03-18 10:01:46  Imported #7391983 0xe123…9b58 (8.00 Mgas)
2019-03-18 10:02:03  Imported #7391992 0xd180…fc66 (7.99 Mgas)
2019-03-18 10:02:13  Imported #7391993 0x6065…7e13 (7.99 Mgas)
```

**Comment by drewstone** [comment]
The contract is not yet deployed on Mainnet, I'll keep you posted when that happens.
